<div id="header">
				<div id="names"><img src="images/names.png" height="120" width="715"></div><!-- names -->
				<div id="navbar">
				<ul>
            			  <li><a href="index.php">WELCOME</a></li>
            			  <li><a href="engagement.php">ENGAGMENT STORY</a></li>
                		  <li><a href="wedding-details.php">WEDDING DETAILS</a></li>
                		  <li><a href="rsvp.php">RSVP</a></li>
                		  <li><a href="">PHOTO GALLERY</a></li>
                		  <li><a href="http://www.bedbathandbeyond.com/regGiftRegistry.asp?wrn=%2D951621439&">REGISTRY</a></li>
            			</ul>
				</div><!-- navbar -->
			</div><!-- header -->
