        <div id="header">
            <div id="names">
                <img src="images/names.png" height="120" width="715" />
            </div><!-- names -->

            <div id="navbar">
                <ul>
                    <li><a href="index.php">Welcome</a></li>

                    <li><a href="engagement.php">Engagement Story</a></li>

                    <li><a href="wedding-details.php">Wedding Details</a></li>

                    <li><a href="javascript:void(0)" onclick="javascript:window.open('https://docs.google.com/spreadsheet/viewform?formkey=dEI5SmVnZUhnVW1qLXRQZHlIZTVwWGc6MQ', 'RSVP Form','menubar=0, toolbar=0, directories=0, location=0, location=1,status=1,scrollbars=1, width=650,height=515')">RSVP</a></li>

                    <li><a href="photo-gallery.php">Photo Gallery</a></li>

                    <li><a href="registry.php">Registry</a></li>
                </ul>
            </div><!-- navbar -->
        </div><!-- header -->
