<div id="header">
				<div id="names"><img src="images/names.png" height="120" width="715"></div><!-- names -->
				<div id="navbar">
				<ul>
            			  <li><a href="index.php">Welcome</a></li>
            			  <li><a href="engagement.php">Engagement Story</a></li>
                		  <li><a href="wedding-details.php">Wedding Details</a></li>
                		  <li><a href="rsvp.php">RSVP</a></li>
                		  <li><a href="photo-gallery.php">Photo Gallery</a></li>
                		  <li><a href="http://www.bedbathandbeyond.com/regGiftRegistry.asp?wrn=%2D951621439&">Registry</a></li>
            			</ul>
				</div><!-- navbar -->
			</div><!-- header -->
